barbearia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('usuarios.urls')),
    path('agendamentos/', include('agendamentos.urls')),
    path('cliente/', include('cliente.urls')),
    path('estoque/', include('estoque.urls')),
    path('servicos/', include('servicos.urls')),
    path('vendas/', include('vendas.urls')),
]  

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cliente/urls.py
# cliente/urls.py
from django.urls import path
from . import views

app_name = 'cliente'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('novo_agendamento/', lambda request: redirect('agendamentos:criar_agendamento'), name='novo_agendamento'),
    
]

vendas/urls.py
from django.urls import path


urlpatterns = [
    
]

templates/base.html
{% load static %}

<!doctype html>
<html lang="pt-BR">
  <head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'usuarios/css/base.css' %}">
   
    {% block 'head' %}
    
    {% endblock  %}
    
    <title>{% block 'title' %} {% endblock  %}</title>
  </head>

  <body class="fundo">

    <nav class="navbar navbar-expand-lg navbar-dark bg-nav">
      <a class="navbar-brand" href="{% url "cliente:home" %}">BARBER-SHOP</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url "login" %}">login <span class="sr-only">(current)</span></a>
          </li>
          <li class="navbar-nav">
            <a class="nav-link active" href="{% url 'cadastro' %}" class="btn ">Cadastrar</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url "sair" %}">Sair</a>
          </li>
          
        </ul>
      </div>
    </nav>




    {% block 'body' %}
     
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    
  </body>
</html>

templates/cliente_base.html
{% load static %}

<!doctype html>
<html lang="pt-BR">
  <head>
    
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'cliente/css/base.css' %}">
   
    
    {% block 'head' %}
    {% endblock  %}
    
    <title>{% block 'title' %} {% endblock  %}</title>
  </head>

  

    {% block 'body' %}
    
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    
  </body>
</html>